name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -s --insecure http://localhost:9200/_cluster/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, curl
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check Elasticsearch
      run: |
        echo "Checking Elasticsearch..."
        curl -s --insecure http://localhost:9200

    - name: Wait for Elasticsearch
      run: |
        echo "Waiting for Elasticsearch to be ready..."
        for i in {1..30}; do
          if curl -s --insecure http://localhost:9200/_cluster/health | grep -q '"status":"green\|yellow"'; then
            echo "Elasticsearch is ready!"
            break
          fi
          echo "Waiting... ($i/30)"
          sleep 2
        done
        curl -s --insecure http://localhost:9200/_cluster/health

    - name: Run test suite
      run: vendor/bin/pest